begin;

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  session_id text not null unique,
  stage text,
  last_event text,
  name text,
  cpf text,
  email text,
  phone text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  utm_term text,
  utm_content text,
  gclid text,
  fbclid text,
  ttclid text,
  referrer text,
  landing_page text,
  source_url text,
  user_agent text,
  client_ip text,
  gateway text,
  pix_txid text,
  pix_amount numeric(12,2),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.leads add column if not exists gateway text;
alter table public.leads add column if not exists pix_txid text;
alter table public.leads add column if not exists pix_amount numeric(12,2);
alter table public.leads add column if not exists cep text;
alter table public.leads add column if not exists address_line text;
alter table public.leads add column if not exists number text;
alter table public.leads add column if not exists complement text;
alter table public.leads add column if not exists neighborhood text;
alter table public.leads add column if not exists city text;
alter table public.leads add column if not exists state text;
alter table public.leads add column if not exists reference text;
alter table public.leads add column if not exists shipping_id text;
alter table public.leads add column if not exists shipping_name text;
alter table public.leads add column if not exists shipping_price numeric(12,2);
alter table public.leads add column if not exists bump_selected boolean not null default false;
alter table public.leads add column if not exists bump_price numeric(12,2) not null default 0;

-- Privacidade do quiz: remove respostas individuais antigas e mantém apenas
-- score, total, status e tempos agregados no objeto quiz.
update public.leads
set payload = case
  when jsonb_typeof(payload -> 'quiz') = 'object'
    then jsonb_set(
      payload - 'answers' - 'quizAnswers' - 'quizResponses',
      '{quiz}',
      (payload -> 'quiz') - 'answers' - 'responses' - 'questions' - 'selections' - 'quizAnswers' - 'quizResponses',
      true
    )
  else payload - 'answers' - 'quizAnswers' - 'quizResponses'
end
where payload ? 'answers'
   or payload ? 'quizAnswers'
   or payload ? 'quizResponses'
   or (
     jsonb_typeof(payload -> 'quiz') = 'object'
     and (
       (payload -> 'quiz') ? 'answers'
       or (payload -> 'quiz') ? 'responses'
       or (payload -> 'quiz') ? 'questions'
       or (payload -> 'quiz') ? 'selections'
       or (payload -> 'quiz') ? 'quizAnswers'
       or (payload -> 'quiz') ? 'quizResponses'
     )
   );

create or replace function public.sanitize_lead_quiz_payload()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if jsonb_typeof(new.payload) <> 'object' then
    new.payload := '{}'::jsonb;
  end if;

  new.payload := new.payload - 'answers' - 'quizAnswers' - 'quizResponses';
  if jsonb_typeof(new.payload -> 'quiz') = 'object' then
    new.payload := jsonb_set(
      new.payload,
      '{quiz}',
      (new.payload -> 'quiz') - 'answers' - 'responses' - 'questions' - 'selections' - 'quizAnswers' - 'quizResponses',
      true
    );
  end if;
  return new;
end;
$$;

drop trigger if exists leads_sanitize_quiz_payload on public.leads;
create trigger leads_sanitize_quiz_payload
before insert or update of payload on public.leads
for each row execute function public.sanitize_lead_quiz_payload();

revoke all on function public.sanitize_lead_quiz_payload() from public, anon, authenticated;
grant execute on function public.sanitize_lead_quiz_payload() to service_role;

create index if not exists leads_updated_at_idx on public.leads (updated_at desc);
create index if not exists leads_email_idx on public.leads (email);
create index if not exists leads_phone_idx on public.leads (phone);
create index if not exists leads_client_ip_idx on public.leads (client_ip);
create index if not exists leads_pix_txid_idx on public.leads (pix_txid);

create table if not exists public.lead_pageviews (
  id bigint generated by default as identity primary key,
  session_id text not null,
  page text not null,
  created_at timestamptz not null default now(),
  unique (session_id, page)
);
create index if not exists lead_pageviews_session_idx on public.lead_pageviews (session_id, created_at);
create index if not exists lead_pageviews_page_idx on public.lead_pageviews (page, created_at desc);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.event_dispatch_queue (
  id bigint generated by default as identity primary key,
  channel text not null check (channel in ('utmfy', 'pushcut', 'pixel')),
  event_name text,
  kind text,
  payload jsonb not null default '{}'::jsonb,
  dedupe_key text,
  status text not null default 'pending' check (status in ('pending', 'processing', 'completed', 'failed')),
  attempts integer not null default 0 check (attempts >= 0),
  last_error text,
  scheduled_at timestamptz not null default now(),
  processed_at timestamptz,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);
drop index if exists public.dispatch_queue_dedupe_idx;
create unique index if not exists dispatch_queue_dedupe_idx on public.event_dispatch_queue (dedupe_key);
create index if not exists dispatch_queue_pending_idx on public.event_dispatch_queue (status, scheduled_at, id);
create index if not exists dispatch_queue_updated_idx on public.event_dispatch_queue (updated_at desc);

create table if not exists public.security_clone_events (
  id bigint generated by default as identity primary key,
  event_type text,
  page text,
  reported_host text,
  official_host text,
  href text,
  referrer text,
  origin text,
  source_url text,
  screen text,
  timezone text,
  language text,
  user_agent text,
  client_ip text,
  risk_score integer not null default 0 check (risk_score between 0 and 100),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.security_clone_events add column if not exists event_type text;
alter table public.security_clone_events add column if not exists page text;
alter table public.security_clone_events add column if not exists reported_host text;
alter table public.security_clone_events add column if not exists official_host text;
alter table public.security_clone_events add column if not exists href text;
alter table public.security_clone_events add column if not exists referrer text;
alter table public.security_clone_events add column if not exists origin text;
alter table public.security_clone_events add column if not exists source_url text;
alter table public.security_clone_events add column if not exists screen text;
alter table public.security_clone_events add column if not exists timezone text;
alter table public.security_clone_events add column if not exists language text;
alter table public.security_clone_events add column if not exists user_agent text;
alter table public.security_clone_events add column if not exists client_ip text;
alter table public.security_clone_events add column if not exists risk_score integer not null default 0;
alter table public.security_clone_events add column if not exists payload jsonb not null default '{}'::jsonb;
alter table public.security_clone_events add column if not exists created_at timestamptz not null default now();
create index if not exists clone_events_created_idx on public.security_clone_events (created_at desc);
create index if not exists clone_events_ip_idx on public.security_clone_events (client_ip, created_at desc);
create index if not exists clone_events_risk_idx on public.security_clone_events (risk_score desc, created_at desc);

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  action text not null,
  client_ip text,
  user_agent text,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists admin_audit_created_idx on public.admin_audit_logs (created_at desc);

drop view if exists public.leads_readable;
create view public.leads_readable
with (security_invoker = true) as
  select * from public.leads;
drop view if exists public.pageview_counts;
create view public.pageview_counts
with (security_invoker = true) as
  select page, count(*)::bigint as views, max(created_at) as last_view_at
  from public.lead_pageviews
  group by page;

alter table public.leads enable row level security;
alter table public.lead_pageviews enable row level security;
alter table public.app_settings enable row level security;
alter table public.event_dispatch_queue enable row level security;
alter table public.security_clone_events enable row level security;
alter table public.admin_audit_logs enable row level security;

revoke all on public.leads from anon, authenticated;
revoke all on public.lead_pageviews from anon, authenticated;
revoke all on public.app_settings from anon, authenticated;
revoke all on public.event_dispatch_queue from anon, authenticated;
revoke all on public.security_clone_events from anon, authenticated;
revoke all on public.admin_audit_logs from anon, authenticated;
grant all on public.leads to service_role;
grant all on public.lead_pageviews to service_role;
grant all on public.app_settings to service_role;
grant all on public.event_dispatch_queue to service_role;
grant all on public.security_clone_events to service_role;
grant all on public.admin_audit_logs to service_role;
grant select on public.leads_readable to service_role;
grant select on public.pageview_counts to service_role;

commit;
